In [3]:
import numpy as np

In [4]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
a = np.array([1, 2, 3, 4, 5, 7, 12])
a

array([ 1,  2,  3,  4,  5,  7, 12])

In [9]:
a[2] = 10

In [10]:
a    

array([ 1,  2, 10,  4,  5,  7, 12])

In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [13]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [15]:
n[0, 1] = 20

In [16]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [17]:
n[2] = [1, 1, 1]

In [18]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [19]:
n[:, 1] = [0, 1, 2]

In [20]:
n

array([[1, 0, 3],
       [4, 1, 6],
       [1, 2, 1]])

In [21]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [22]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [23]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [39]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [42]:
b = (10 + (a * 2)) ** 2 / 100

In [43]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [46]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

In [ ]:
a >= 2

array([False, False,  True,  True,  True])

In [50]:
a[a > b]

array([2, 3, 4])

In [54]:
a.std()

np.float64(1.4142135623730951)

In [61]:
np.median(a)

np.float64(2.0)

In [67]:
assert a.shape[0] == b.shape[0]

In [78]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [79]:
v = np.array([1, 0, 0, 2])

In [83]:
def vector_vector_mult(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [84]:
def matrix_vector_mult(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_mult(U[i], v)
    return result

In [85]:
matrix_vector_mult(U, v)

array([14.,  5.,  5.])

In [86]:
U.dot(v)

array([14,  5,  5])

In [87]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [95]:
def matrix_matrix_mult(U, V):
    assert U.shape[1] == V.shape[0]
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_mult(U, vi)
        result[:, i] = Uvi
        
    return result

In [96]:
matrix_matrix_mult(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [97]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])